sveltejs/svelte.technology

src/guide/01-component-api.md, src/guide/04-behaviour.md
The acronym's definition comes in section 4. This changes it so that it is spelled out on first reference in section 2 and referred to as `POJO` in section 4.
=> Spell out POJO on first reference

src/guide/04-behaviour.md, src/guide/05-element-directives.md
Using the functions in the docs gives warnings like this:
```
(23:4) – 'onrender' has been deprecated in favour of 'oncreate', and will cause an error in Svelte 2.x
(28:4) – 'onteardown' has been deprecated in favour of 'ondestroy', and will cause an error in Svelte 2.x
```
So this brings the guide up to date.
=> Replace deprecated functions `onrender` and `onteardown`.

src/repl/Repl.html, src/repl/components/CodeMirror.html, src/repl/components/Viewer.html, src/repl/examples.js, src/repl/main.js
This is an initial stab at #51. The examples are all bundled into repl.js, which I don't think is *too* much of a problem. There was a little funkiness I had to work around - when you initialize the REPL you have to do so via `data` and when you load a different example later you have to do so via `json`. But switching examples, loading `data=` links from the guide, and loading examples from gists *should* theoretically be all working.
=> move examples from gists into repo (#51)

shared/routes/Index.html
Removes the words "obesity" and "stupid" to use more positive language as suggested by @wavebeem
Closes #13
=> Improve homepage phrasing

server/templates/index.html
While I was taking a look at the page source, I noticed that it was using an invalid DOCTYPE and getting parsed in quirks mode as a result.
Using Firefox I didn't see any immediate difference in rendering after making this change, but I still figured I'd submit a PR to avoid accidental reliance on quirks in future changes. The Rollup website is also affected.
I decided to keep the newline which my editor inserted at the end of the file, given that it's used inconsistently in this repo right now.
_Seeing as I have the opportunity, I'd also like to say thanks for all the work you've put into your open source projects. It's inspiring to see someone willing and able to tackle so many large problems and find their own creative ways of solving them._
=> Fix DOCTYPE

shared/routes/Repl/CodeMirror.html
There's some other animation stuff here that doesn't seem to be working and I couldn't figure out how it was supposed to work. But this `opacity: 0` was definitely breaking things. The error messages associated with the CodeMirror components were not actually visible.
=> repl: fix displaying of error messages

guide/00-introduction.md, guide/01-component-api.md, guide/04-behaviour.md, guide/05-element-directives.md, shared/components/GuideContents.html, shared/routes/Guide.html, shared/routes/Repl/CodeMirror.html, shared/routes/Repl/Viewer.html, shared/routes/Repl/index.html
The deprecated method onrender() is used in one of the examples.
Change to oncreate().
See sveltejs/svelte#40
=> Change deprecated onrender to oncreate

shared/routes/Repl/utils/gist.js
=> repl: mark App.html as the entry component when loading from a gist

.gitignore, package.json, scripts/prep/build-components.js, scripts/prep/build-repl.js, server/index.js, shared/routes/Repl/CodeMirror.html, shared/routes/Repl/Viewer.html, shared/routes/Repl/index.html, shared/routes/Repl/utils/getLocationFromStack.js, yarn.lock
This falls under #39. When an error occurs, it's often possible to trace the last item in the stack back to a location in the component source code. We can use that information to help users diagnose the error.
I've got as far as this:
=> Show origin of runtime errors

shared/routes/Repl/CodeMirror.html
Fixes the particular instance of #89 that I was seeing. I've made the error message display in `CodeMirror.html` align with that in `Viewer.html`, so that if `error.loc` is undefined, it won't crash the whole REPL.
=> repl: in CodeMirror component, deal with `error.loc` being undefined

shared/components/Nav.html
Fixes nav display in Safari #95
=> Nav component: add overflow-y only when open

server/manifests/bundle.json, shared/routes/Repl/index.html
This adds the ability to toggle between 'ssr' and 'dom' in the REPL.
There is likely some work to be done here in terms of animations, naming, and bike shedding.
=> Add ability to view compiled ssr code with repl

universal/routes/Repl/Viewer.html
=> destroy _svelteTransitionManager when creating fresh components

guide/02-template-syntax.md
Simple fix for #106 — just don't allow those examples to be opened in the REPL
=> disable REPL for examples that aren't REPL-friendly

content/guide/01-component-api.md
Noticed this wasn't mentioned in the guide.
=> document `component.get()` with no arguments

templates/service-worker.js
The REPL is failing to save-as-gist, apparently because the service worker balks at POST requests
=> don't handle POST requests in service worker

content/examples/7guis-temperature/App.html
=> fix typo in temperature converter example

content/guide/09-server-side-rendering.md
fixes #186. Links to a currently non-existent section on `<:Head>` — PR for #171 coming shortly
=> update SSR docs

content/guide/01-component-api.md
This feels a bit skimpy, but if we're not steering people toward using this for DI etc., I'm not sure what else there is to say really.
=> document `component.root` (#169)

content/examples/binding-media-elements/App.html, content/examples/binding-media-elements/example.json, content/examples/manifest.json, content/examples/parallax/App.html, content/examples/transitions-custom/App.html, content/examples/transitions-custom/example.json, content/examples/transitions-fade/App.html, content/examples/transitions-fade/example.json, content/examples/transitions-fly/App.html, content/examples/transitions-fly/example.json, content/examples/transitions-in-out/App.html, content/examples/transitions-in-out/example.json, routes/repl/index.html
Preparing a talk for this evening and found a couple of examples that ought to be tweaked.
This PR also switches the REPL to compiling in dev mode, which among other things enables CSS sourcemaps. In the longer term this should probably be a REPL option, and the CSS should be extracted out since it looks somewhat bulky when added inline with a sourcemap. But it solves the immediate problem...
=> tweak examples, compile in dev mode

routes/repl/_worker.js, routes/repl/index.html
Rather than recreating the REPL worker every time the REPL is recreated (say, you're toggling back and forth between the REPL and the guide), this keeps the original worker and caches Svelte locally, speeding things up greatly on repeat visits
=> reuse worker and cache svelte

content/guide/00-introduction.md, content/guide/10-server-side-rendering.md
Resolves #286. These are largely adapted from the `svelte-cli` readme. I don't think we want to spend too much time on these, since we're discouraging the CLI's use.
I also put a deprecation note in the svelte-cli repo's readme.
=> add some brief CLI docs

routes/repl/_components/AppControls.html
This should reduce some confusion that people have had over the greyed-out 'save' button. Before, you could only save your own gists. Now, if you're not on a gist (i.e. you're on an example) or it's not your gist, then clicking 'save' (or hitting Cmd-S) will call `fork()` behind the scenes.
=> fork if user hits save but does not own gist

content/examples/immutable/App.html, content/examples/immutable/ImmutableTodo.html, content/examples/immutable/MutableTodo.html, content/examples/immutable/data.json5, content/examples/manifest.json, content/guide/13-advanced.md
I think it's nicer to have all of the examples in the docs be at `demo=` URLs rather than having them live in gists. I'm not entirely happy with the title and location of the example in `manifest.json`, so if you're got a better idea for that, please go for it
=> move immutable demo from gist to a built-in example

content/guide/06-special-components.md
Should address #374. Or at least be a start.
I tried adding an example, but the REPL wasn't working as expected:
```html
<svelte:document on:mouseenter='set({ entered: true })' />
<p>The mouse is {entered ? 'in' : 'out'}</p>
<script>
export default {
data() {
return { entered: false }
}
}
</script>
```
Maybe that's because how the REPL is built?
=> Document <svelte:document>

content/guide/11-state-management.md
The docs were already pretty clear on this but some people (myself included) didn't actually put two and two together that they were the same properties
=> Make store state events' properties more obvious
