- src/repl/examples.js
This adds examples of a basic line chart + responsive area and bar charts to the Svelte.technology REPL.
> adds charts (line, area, bar)

- src/guide/02-template-syntax.md
> guide: document triples

- src/repl/components/CodeMirror.html
> repl: correctly show error indicator when at pos 0

- src/guide/01-component-api.md
I'm just trying to update the docs where I was missing something :)
> Document how to use observe on a child widget

- src/guide/05-element-directives.md
I think this example helps a lot in understanding how Svelte does forms and therefore think it should be part of the docs. Thanks to Richard Harris for creating it (https://svelte.technology/repl/?version=1.6.11&gist=73723154e19813baa24d54ac3d3d322f)
> Add example of form handling.

- gobblefile.js
- src/repl/version.js
Fixes a bunch of linting issues.
> Fix linting

- public/magic-string.umd.js
- server/templates/index.html
Svelte doesn't have an external dependency on magic-string any more, but old versions (i.e. any REPL links shared prior to a few days ago) still need it
> Reinstate magic string

- examples/hello-world/App.html
- examples/manifest.json
- examples/parallax/App.html
- examples/parallax/example.json
- scripts/prep/build-examples.js
- shared/routes/Repl/ExampleSelector.html
- shared/routes/Repl/index.html
This divides examples up into categories, so we can add more of them without it all becoming overwhelmingly confusing
> [WIP] Better examples

- shared/routes/Repl/Viewer.html
> Fixed curl service's context in REPL viewer

- scripts/svelte-app/package.json
> Default Hello World Download Doesn't Build

- universal/routes/Repl/ComponentSelector.html
- universal/routes/Repl/index.html
Here is a gif below to show it in action.
> Change REPL to use tabs instead of dropdown

- server/manifests/bundle.json
- server/manifests/css.json
- universal/routes/Repl/Viewer.html
Addresses #103 in the hackiest way possible. Would be nice to do this properly, eventually, but I kind of need this for a demo later... 😬
> only autorun if no oncreate

- universal/routes/Repl/CodeMirror.html
- universal/routes/Repl/Viewer.html
- universal/routes/Repl/index.html
We could get more sophisticated with this (highlighting areas in the source code, etc) but this'll do for now.
> show if warnings were generated

- examples/bar-chart/App.html
- examples/line-chart/App.html
These now show up as warnings in the REPL
> remove unused selectors

- guide/04-behaviour.md
Just a note for now - I don't know if there is a desire to add a section on building/bundling svelte with full details and examples, but it doesn't feel like it belongs here.
> Clarity around build step ordering

- guide/04-behaviour.md
FWIW the newline at the end of the file was added by Github, not me.
> Fix method name reference

- universal/routes/Repl/ComponentSelector.html
- universal/routes/Repl/index.html
- yarn.lock
While I was at it, tweaked `<ComponentSelector>` so that if you type in `Foo.html` it doesn't try and turn it into `Foo.html.html`
> error if components have the same name. closes #84

- examples/hacker-news/App.html
- examples/hacker-news/Comment.html
- examples/hacker-news/Item.html
- examples/hacker-news/List.html
- examples/hacker-news/Summary.html
- examples/hacker-news/TimeAgo.html
- examples/hacker-news/example.json
- examples/hacker-news/store.js
- examples/manifest.json
- package.json
- scripts/prep/build-examples.js
- server/manifests/bundle.json
- server/manifests/css.json
- universal/routes/Repl/CodeMirror.html
- universal/routes/Repl/ComponentSelector.html
- universal/routes/Repl/Viewer.html
- universal/routes/Repl/index.html
- universal/routes/Repl/utils/gist.js
- yarn.lock
> Implement .js files, add HN example

- universal/routes/Repl/Viewer.html
Since https://github.com/Rich-Harris/packd/issues/10
> Use bundle.run CDN

- guide/02-template-syntax.md
since we have #259 and #301 and I still wrote https://stackoverflow.com/questions/45714809/sveltejs-render-html-attribute-conditionally on top of it, I thought it is worth explaining boolean attributes in the guide :-)
> Explain handling of boolean attributes

- src/universal/routes/Repl/index.html
> handle compilation errors when loading from gist

- content/guide/09-server-side-rendering.md
According to sveltejs/svelte#940
> Update SSR documentation for the new bootstrapping with options

- content/guide/04-behaviour.md
> clarify instance data

- package.json
- rollup.config.js
- scripts/prep/build-blog.js
- scripts/prep/build-guide.js
- src/server/index.js
- src/universal/Page.html
- yarn.lock
> don't hash service worker URL

- src/client/main.js
- src/universal/components/Toast.html
> show toast when content changes, prompt for reload

- content/examples/await-block/App.html
- content/examples/await-block/example.json
- content/examples/manifest.json
- content/guide/02-template-syntax.md
> await block documentation

- content/examples/7guis-circles/App.html
- content/examples/7guis-crud/App.html
- content/examples/7guis-flight-booker/App.html
- content/examples/7guis-temperature/App.html
- content/examples/7guis-timer/App.html
- content/examples/area-chart/example.json
- content/examples/bar-chart/App.html
- content/examples/binding-media-elements/App.html
- content/examples/binding-textarea/App.html
- content/examples/line-chart/App.html
- content/examples/scatterplot/Scatterplot.html
- content/examples/svg-clock/App.html
- content/guide/00-introduction.md
- content/guide/01-component-api.md
- content/guide/04-behaviour.md
- content/guide/05-nested-components.md
- content/guide/07-element-directives.md
- content/guide/08-plugins.md
- content/guide/09-static-properties.md
Removes all the jQuery-style excess spacing, and uses ES6 consistently (it's 2018 after all)
> Code style

- content/guide/07-element-directives.md
- content/guide/08-plugins.md
- routes/api/guide/_sections.js
- routes/api/guide/contents.js
- routes/api/guide/index.js
> Transitions

- content/guide/13-advanced.md
> document hydration

- routes/repl/_Viewer.html
Hopefully fixes the important part of #202 - namely the part seen in https://github.com/sveltejs/svelte/issues/1068 This looked to me like it was working.
> repl: fix watching removed and reinstated data properties

- content/guide/04-behaviour.md
@arxpoetica suggested this be added. Actual text just a first draft.
> Update 04-behaviour.md with better explanation of using external funcs in computed

- content/guide/10-server-side-rendering.md
Just updating the package name reference after the rename.  While the package is published and ready I'm presenting this PR so changes can land before or along with the release blog next week.
> Update std/esm reference.

- routes/gist/[id].js
- routes/repl/_components/ModuleEditor.html
- routes/repl/_worker.js
- routes/repl/index.html
> show compiled output

- package.json
- routes/repl/_components/ComponentSelector.html
- routes/repl/_worker.js
- routes/repl/index.html
- yarn.lock
closes #226, albeit hackily — for some reason the component wasn't being passed through as an argument. need to investigate
> fix component removal

- app/server.js
- routes/repl/_components/AppControls.html
- routes/repl/_components/UserMenu.html
A couple of fixes, possibly more to come.
> GitHub fixes

- app/server.js
- routes/repl/_components/AppControls.html
It'd probably be best if you tried this out locally yourself, but from my tests this works whether or not you need to interact with the popup window, and whether you are on firefox or chrome.
> fix handling of message from login window

- app/server.js
This allows anyone to start up the app, and adds some instructions if you want to test auth stuff in addition
> make auth stuff optional

- routes/repl/_components/AppControls.html
> fix saving data.json when updating gist (#241)

- routes/repl/_components/ComponentSelector.html
- routes/repl/_components/ExampleSelector.html
- routes/repl/_components/events.js
> blur project name input on enter

- routes/repl/_components/AppControls.html
> avoid fat-fingering and overwriting built-in examples

- app/service-worker.js
- package.json
- routes/gist/create.js
- routes/repl/_components/AppControls.html
- routes/repl/index.html
- yarn.lock
This preserves formatting, and is more flexible (keys don't need to be stringified, strings can use single quotes, we can use comments, etc)
> Use golden-fleece

- routes/repl/_components/ComponentSelector.html
fixes #207. Turns out you can't click elements inside buttons in Firefox, for reasons best known to them
> make components deleteable in firefox

- routes/api/guide/_sections.js
- routes/guide/index.html
fixes #244. Hopefully this will reduce the friction for would-be contributors
> add edit link

- content/guide/15-miscellaneous.md
> add misc section, document noscript

- routes/repl/_components/Viewer.html
- routes/repl/_worker.js
- routes/repl/index.html
Provides a preview of what you're working on if one of your components uses `oncreate` or `ondestroy` (in which case we can't update as-you-type). Fixes #247
> render static version of components with lifecycle hooks

- content/guide/01-component-api.md
- content/guide/04-behaviour.md
- content/guide/11-state-management.md
This sea of red makes me happy
> document onstate and onupdate, remove observe docs

- package.json
- routes/repl/_components/Viewer.html
- routes/repl/index.html
- yarn.lock
This changes the mechanism by which data flows between the component and the data editor, which allows the example in #279 to work
> Fix component binding

- routes/repl/_components/ComponentSelector.html
not sure when these broke but it's been annoying me
> fix component tab styles

- content/guide/13-advanced.md
- routes/repl/_worker.js
- routes/repl/index.html
> reinstate compiler error UI

- components/Toast.html
Update the cursor to be a pointer as to indicate its clickable on a desktop
> Change from div to a button for better semantics

- src/routes/guide/index.html
> fix: prefix tab-size for mozilla

- content/guide/07-element-directives.md
> Document event modifiers

- content/guide/01-component-api.md
> Document the "anchor" option

- content/guide/07-element-directives.md
Added an "indeterminate" binding for the checkbox to the doc
> Added "indeterminate" binding

- content/guide/06-special-components.md
I found that if I searched for "dynamic component" for Svelte it didn't give me any results and it took me a while to find that it does have such a thing. I added this keyword to the text, so that others might be able to find it easier.
> Add the keyword "dynamic component"

- content/blog/2019-01-31-svelte-on-the-changelog.md
> add changelog podcast blog post

- src/routes/repl/_components/Viewer.html
- src/routes/repl/_utils/ReplProxy.js
- static/repl-runner.js
- Relaxed most sandbox restrictions
- Fixed two way sync of prop values
- Backport of svelte3 repl cleanups.
> Repl improvements

- content/guide/03-scoped-styles.md
Fixes anchor link to CSS rendering section
> scoped-styles: fix link to css rendering section
